[toolchain]
anchor_version = "0.31.1"
sbf_tools_version = "v1.52"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zol_chess = "8rma9vAqsVAz6pAWFCqnaGTktkzpVk1TWFQsgH3VEh6Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
